import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { UserDataProvider } from "@/context/AuthContext";
import Navbar from "@/components/Layout/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserDataProvider>
          <Navbar />
          {children}
        </UserDataProvider>
      </body>
    </html>
  );
}
